version: '3'

services:
    db:
        image: postgres:16.1-alpine3.17
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: nammtrong023
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: lms
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data

    frontend:
        build:
            context: ./frontend
            dockerfile: frontend.dockerfile
            args:
                FRONTEND_ENV: ${SERVER_URL}
        container_name: frontend
        env_file:
            - .env
        ports:
            - 3000:3000

    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nginx
        depends_on:
            - frontend
        restart: unless-stopped
        ports:
            - 80:80

    backend:
        build:
            context: ./backend
            dockerfile: backend.dockerfile
        container_name: backend
        env_file:
            - .env
        ports:
            - 8000:8000

volumes:
    postgres-data:
